
os: linux
arch:
  - arm64
  - ppc64le
  - s390x
dist: bionic

# safelist
branches:
  only:
  - master
  - testing

# prepare environment
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python python-dev python-virtualenv libgd-dev libgif-dev
  - export PYTHON=$(which python2)
  - virtualenv -p $PYTHON ~/venv
  - source ~/venv/bin/activate
  - pip list

# command to install dependencies
install:
  - pip install -e .[dev,test]

# command to run tests
script: nosetests --with-coverage --cover-package=GClib --cover-erase

after_success:
  - coveralls
