
os: linux
arch:
  - arm64
  - ppc64le
  - s390x
dist: bionic

# safelist
branches:
  only:
  - master
  - testing

language: python

python:
  - "2.7"

# prepare environment
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgd-dev libgif-dev

# command to install dependencies
install:
  - pip install -e .[dev,test]

# command to run tests
script: nosetests --with-coverage --cover-package=GClib --cover-erase

after_success:
  - coveralls
