name: Nosetest workflow

on:
  push:
    branches:
      - master
      - testing
  pull_request:
    branches:
      - master
      - testing


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: '2.7'
          architecture: 'x64'

      - name: Install requirements
        run: sudo apt-get install libgd-dev libgif-dev

      - name: Install dependencies
        run: pip install -e .[dev,test]

      - name: Test with nosetest
        run: nosetests --with-coverage --cover-package=GClib --cover-erase
